logo: # add logo name
title: JinAn - Enjoy Coding
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: JinAn # your name
about-author-now:  Master student from Yale university majoring in biostatistics.
about-author-future: Incoming software engineer of Amazon. # about author
email: aj931128@gmail.com # your email
phone: (203)-285-**** # your pnone number
website: https://jaean1993.github.io # you website

# Social link
google_url: https://plus.google.com/112078908118489064372   # add url link
twitter_url: https://twitter.com/jaean1993  # add url link 
instagram_url: https://www.instagram.com/jin_an_yale/ # add url link
pinterest_url: https://www.pinterest.com/jaean1993/ # add url link
linkedin_url: https://www.linkedin.com/in/jin-an-5b7b1a99/ # add url link
facebook_url: https://www.facebook.com/KlausAn1993 # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: UA-109491630-1

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]